### ISSUE TITLE
Not getting Gaia's Tears on wishing well / Auction tool not working

### ISSUE THREAD

**Issue by morda21** [0rtis/dfktools#5]
I was using wishing well tool for exping heroes. After few days I've noticed that tears gain drastically dropped. Many complete quest transactions were revered. Every revered quest had mined gaia's tears in internal transaction log. Another attempt to finish this quest was succeed but without additional xp/tears.
[reverted tears.txt](https://github.com/0rtis/dfk/files/7573422/reverted.tears.txt)
[succeed quests.txt](https://github.com/0rtis/dfk/files/7573423/succeed.quests.txt)
I figured out that reason of reverting quests with mined tears was lack of maxGasUsed variable in buildTransaction:
```
tx = contract.functions.completeQuest(hero_id).buildTransaction(
        {'gasPrice': w3.toWei(gas_price_gwei, 'gwei'), 'nonce': `nonce})
```
after adding maxGasUsed heroes normally started to earn bonus XP and tears
```
tx = contract.functions.completeQuest(hero_id).buildTransaction(
        {'gasPrice': w3.toWei(gas_price_gwei, 'gwei'), 'nonce': nonce, 'gas': 600000})
```

Another issue is that auction tool stopped working since they changed graphql query. Unfortunately I have no skills to fix this

**Comment by 0rtis** [comment]
By default, the `gas` variable is provided by the RPC service. By setting it manually you might end up paying too much or too little.
I believe that main reason for this issue is the instability of the public RPC caused by the recent price volatility of Harmony.
A better approach would be to adjust the gas if there if several transaction have failed in a short time frame (call `estimateGas` and add a premium on top of it)
